// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu4WS5QJgOnc7GuDe_E489W2_W5EvFPWo',
    appId: '1:431732675397:web:d144795a727fc6499ea42c',
    messagingSenderId: '431732675397',
    projectId: 'evsmart-se1503',
    authDomain: 'evsmart-se1503.firebaseapp.com',
    storageBucket: 'evsmart-se1503.appspot.com',
    measurementId: 'G-H0L0M9X5BE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFNS-Nr2NSI2JrPM-pSgNBkr-BOj5q7WA',
    appId: '1:431732675397:android:84886e3a352335299ea42c',
    messagingSenderId: '431732675397',
    projectId: 'evsmart-se1503',
    storageBucket: 'evsmart-se1503.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdb8fXnodg67cglqUOWzM4cc8AXGAFXxs',
    appId: '1:431732675397:ios:bf82316391c8bf459ea42c',
    messagingSenderId: '431732675397',
    projectId: 'evsmart-se1503',
    storageBucket: 'evsmart-se1503.appspot.com',
    androidClientId: '431732675397-u8fm43osircjrms4mt6u1902qkabqspm.apps.googleusercontent.com',
    iosClientId: '431732675397-aia1d6k4i76d0ctb14rtu9cakj8aivec.apps.googleusercontent.com',
    iosBundleId: 'com.example.evsmart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdb8fXnodg67cglqUOWzM4cc8AXGAFXxs',
    appId: '1:431732675397:ios:bf82316391c8bf459ea42c',
    messagingSenderId: '431732675397',
    projectId: 'evsmart-se1503',
    storageBucket: 'evsmart-se1503.appspot.com',
    androidClientId: '431732675397-u8fm43osircjrms4mt6u1902qkabqspm.apps.googleusercontent.com',
    iosClientId: '431732675397-aia1d6k4i76d0ctb14rtu9cakj8aivec.apps.googleusercontent.com',
    iosBundleId: 'com.example.evsmart',
  );
}
